#!/bin/bash

while read LINE
do
    IFS=$'\t' read -ra PARTS <<< "$LINE"

    FILE=${PARTS[0]}

    if [ -n "$FILE" ]
    then

        LOCAL=${PARTS[1]}

        if [ -z "$LOCAL" ]
        then
            LOCAL=.$FILE
        fi

        echo $FILE -\> $LOCAL

        if [ -f "$FILE" ]
        then
            mkdir -p `dirname $LOCAL`
            cp $FILE $LOCAL
            git add $LOCAL
        elif [ -d "$FILE" ]
        then
            if [ -a "$LOCAL" ]
            then
                rm -fR $FILE
            fi
            cp -r $FILE $LOCAL
            git add $LOCAL
        fi
    else
        echo 
    fi
done < list

git status

