#!/bin/bash



while read LINE
do
    IFS=$'\t' read -ra PARTS <<< "$LINE"

    FILE=${PARTS[0]}

    FILE=`eval echo $FILE`

    if [ -n "$FILE" ]
    then

        LOCAL=${PARTS[1]}

        if [ -z "$LOCAL" ]
        then
            LOCAL=.$FILE
        fi


        if [ -f "$FILE" ]
        then
            mkdir -p `dirname $LOCAL`
            cp -v $FILE $LOCAL
            git add $LOCAL
        elif [ -d "$FILE" ]
        then
            if [ -a "$LOCAL" ]
            then
                rm -f -R $LOCAL
            fi
            cp -r -v $FILE $LOCAL
            git add $LOCAL
        else
            echo $FILE -\> $LOCAL
            echo "    File is missing."
        fi
    else
        echo 
    fi
done < list

git status

