#!/bin/bash

while read FILE
do
    IFS=$'\t' read -ra PARTS <<< "$LINE"

    FILE=${PARTS[0]}

    FILE=`eval echo $FILE`

    if [ -n "$FILE" ]
    then
        LOCAL=${PARTS[1]}

        if [ -z "$LOCAL" ]
        then
            LOCAL=.$FILE
        fi

        echo $LOCAL -\> $FILE

        if [ -f $LOCAL ]
        then
            mkdir -p `dirname $FILE`
            cp -f $LOCAL $FILE
        elif [ -d $LOCAL ]
        then
            if [ -a $FILE ]
            then
                rm -fR $FILE
            fi
            cp -r $LOCAL $FILE
        fi
    fi
done < list

