#!/bin/bash

if [ ! -e $1 ]
then
    echo "Tracked file '$1' doesn't exist. If it was deleted, you'll have to fix the list manually."
fi

LIST=list
TMP=list.tmp

mv -f $LIST $TMP

LOCAL_HOLD=''

while read LINE
do
    IFS=$'\t' read -ra PARTS <<< "$LINE"

    FILE=${PARTS[0]}
    LOCAL=${PARTS[1]}

    if [ "$1" != "$FILE" ]
    then
        if [ -z "$LOCAL" ]
        then
            echo $FILE >> $LIST
        else
            echo $FILE$'\t'$LOCAL >> $LIST
        fi
    else
        LOCAL_HOLD=$LOCAL
    fi
done < $TMP

rm $TMP

git add list

if [ -d $1 ]
then
    git rm -r $LOCAL_HOLD
elif [ -f "$1" ]
then
    git rm $LOCAL_HOLD
fi

git status

